apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow-container
          image: apache/airflow:2.7.0
          ports:
            - containerPort: 8080  # Porta do Apache Airflow
          volumeMounts:
            - name: dags-volume
              mountPath: /home/guilherme/dev/airflow_rev3/dags
            - name: logs-volume
              mountPath: /home/guilherme/dev/airflow_rev3/logs
            - name: plugins-volume
              mountPath: /home/guilherme/dev/airflow_rev3/plugins
            - name: config-volume
              mountPath: /home/guilherme/dev/airflow_rev3/config
            - name: venv-volume
              mountPath: /home/guilherme/dev/airflow_rev3/venv
      volumes:
        - name: dags-volume
          emptyDir: {}
        - name: logs-volume
          emptyDir: {}
        - name: plugins-volume
          emptyDir: {}
        - name: config-volume
          emptyDir: {}
        - name: venv-volume
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: airflow-service
spec:
  selector:
    app: airflow
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
